SET foreign_key_checks = 0;

DROP TABLE IF EXISTS publisher;
CREATE TABLE publisher (
`id` INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
`name` VARCHAR(255) NOT NULL
);


DROP TABLE IF EXISTS author;
CREATE TABLE author (
`id` INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
`first_name` VARCHAR(100) NOT NULL,
`last_name` VARCHAR(100) NOT NULL
);


DROP TABLE IF EXISTS book;
CREATE TABLE book (
`id` INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
`author_id` INT UNSIGNED NOT NULL,
`publisher_id` INT UNSIGNED NOT NULL,
`title` VARCHAR(255) NOT NULL,`description` TEXT NOT NULL,
`genre` VARCHAR(255) NOT NULL,`format` VARCHAR(255)  NOT NULL,
`lang` VARCHAR(255) NOT NULL,`stock` SMALLINT NOT NULL,
`pages` SMALLINT UNSIGNED NOT NULL,`rating` DECIMAL(3,2) NOT NULL,
`isbn` VARCHAR(13) NOT NULL,
CONSTRAINT `fk_book_author` FOREIGN KEY (`publisher_id`) REFERENCES `publisher`(`id`) ON UPDATE CASCADE ON DELETE SET NULL,
CONSTRAINT `fk_book_publisher` FOREIGN KEY (`publisher_id`) REFERENCES `publisher`(`id`) ON UPDATE CASCADE ON DELETE SET NULL
);


DROP TABLE IF EXISTS member;
CREATE TABLE member (
`id` INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
`username` VARCHAR(100) NOT NULL,
`password` VARCHAR(255) NOT NULL,
`auth` TINYINT NOT NULL DEFAULT 2
);


SET foreign_key_checks = 1;